name: sori_cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.4

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  dio: ^5.9.0
  args: ^2.7.0
  tint: ^2.0.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
